services:
  calendar-server:
    build: .
    container_name: calendar-server
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./uploads/resources.json:/app/uploads/resources.json
      - ./uploads/users.json:/app/uploads/users.json
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    user: "${UID:-1000}:${GID:-1000}"
